#ifndef SHTTPD_TYPE_H
#define SHTTPD_TYPE_H

#define HTTP_OK_ ENCODE_("HTTP/1.1 200 OK\r\n")

#define HTTP_NOT_FOUND_ ENCODE_("HTTP/1.1 404 NOT FOUND\r\n")

#define HTTP_TYPE_ ENCODE_("Content-Type:%S\r\n")

#define NEW_LINE_ ENCODE_("\r\n")

typedef enum request_type
{
	GET=0,
	POST=1
}REQUEST_TYPE;

typedef struct http_request
{
	REQUEST_TYPE type;
	C_STRING path;
	C_STRING get;
	C_STRING post;

	/*common cgi var*/
	size_t CONTENT_LENGTH;
	C_STRING CONTENT_TYPE;
	C_STRING HTTP_ACCEPT;
	C_STRING HTTP_ACCEPT_CHARSET;
	C_STRING HTTP_ACCEPT_ENCODING;
	C_STRING HTTP_ACCEPT_LANGUAGE;
	C_STRING HTTP_COOKIE;
	C_STRING HTTP_REFERER;
	C_STRING HTTP_USER_AGENT;
	C_STRING QUERY_STRING;
	C_STRING REMOTE_ADDR;
}HTTP_REQUEST;

#endif